# Docker Compose simplificado - Solo API (Frontend + Backend)
version: '3.8'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: shameless-api
    restart: unless-stopped
    
    environment:
      # Configuraci칩n b치sica
      - LOG_LEVEL=${LOG_LEVEL:-INFO}
      - API_DEBUG=${API_DEBUG:-false}
      
      # Modelo ML
      - MODEL_NAME=${MODEL_NAME:-distilbert-base-uncased-finetuned-sst-2-english}
      - MODEL_VERSION=${MODEL_VERSION:-v1.0}
      - MODEL_DEVICE=${MODEL_DEVICE:-cpu}
      - MODEL_BATCH_SIZE=${MODEL_BATCH_SIZE:-32}
      
      # Base de datos SQLite (incluida en el contenedor, sin servicio externo)
      - DATABASE_URL=${DATABASE_URL:-sqlite:///./sentiment_analyser.db}
      
      # Credenciales Bluesky (REQUERIDO)
      - BLUESKY_HANDLE=${BLUESKY_HANDLE}
      - BLUESKY_PASSWORD=${BLUESKY_PASSWORD}
      
      # Twitter/X (opcional)
      - TWITTER_API_KEY=${TWITTER_API_KEY:-}
      - TWITTER_API_KEY_SECRET=${TWITTER_API_KEY_SECRET:-}
      - TWITTER_ACCESS_TOKEN=${TWITTER_ACCESS_TOKEN:-}
      - TWITTER_ACCESS_TOKEN_SECRET=${TWITTER_ACCESS_TOKEN_SECRET:-}
      
      # DeepSeek API (para an치lisis de personalidad)
      - DEEPSEEK_API_TOKEN=${DEEPSEEK_API_TOKEN}
      
      # Seguridad
      - SECRET_KEY=${SECRET_KEY:-change-this-in-production}
    
    volumes:
      # Solo persistir datos y logs (NO el c칩digo para evitar conflictos)
      - ./Sentiment_Analyser/data:/app/Sentiment_Analyser/data
    
    ports:
      - "${API_PORT:-8000}:8000"
    
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/docs"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
